# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: javascript / main

on:
  push:
    branches: [main]

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '16'

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci precheck (checks config, lint code, and runs tests) for all exercises
        run: npx babel-node scripts/ci-check

  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16', '17', '18']

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci (checks config, lint code, and runs tests) for all exercises
        run: npx babel-node scripts/ci
